version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/coffee_backend/Dockerfile
    container_name: coffee-backend
    volumes:
      - ./backend/coffee_backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge