# Generated by Django 5.1.7 on 2026-02-03 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0005_coffee_is_community_winner_challenge_notification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coffee_type",
                    models.CharField(
                        choices=[
                            ("espresso", "Espresso"),
                            ("double_espresso", "Double Espresso"),
                            ("americano", "Americano"),
                            ("cappuccino", "Cappuccino"),
                            ("latte", "Latte"),
                            ("mocha", "Mocha"),
                            ("macchiato", "Macchiato"),
                            ("flat_white", "Flat White"),
                            ("cold_brew", "Cold Brew"),
                            ("iced_coffee", "Iced Coffee"),
                            ("drip_coffee", "Drip Coffee"),
                            ("french_press", "French Press"),
                            ("pour_over", "Pour Over"),
                            ("aeropress", "Aeropress"),
                            ("decaf", "Decaf"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("coffee_name", models.CharField(blank=True, max_length=200)),
                (
                    "serving_multiplier",
                    models.FloatField(
                        default=1.0, help_text="Multiplier for serving size"
                    ),
                ),
                (
                    "caffeine_mg",
                    models.FloatField(
                        blank=True, help_text="Caffeine in milligrams", null=True
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumptions",
                        to="coffee.coffee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-consumed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-consumed_at"],
                        name="coffee_coff_user_id_827dd3_idx",
                    )
                ],
            },
        ),
    ]
