# Generated by Django 5.1.7 on 2026-02-03 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0006_coffeeconsumption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="caffeine_mg",
            field=models.FloatField(
                default=95.0,
                help_text="Caffeine content in milligrams (default: 95mg for standard cup)",
            ),
        ),
        migrations.CreateModel(
            name="BloodPressureEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(
                        help_text="Systolic pressure (big number)",
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        help_text="Diastolic pressure (small number)",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True,
                        help_text="Heart rate/pulse",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_pressure_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsumedCoffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumed_by",
                        to="coffee.coffee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumed_coffees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-consumed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserHealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True,
                        help_text="Height in centimeters",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Weight in kilograms",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "has_family_history_chd",
                    models.BooleanField(
                        default=False,
                        help_text="Family history of coronary heart disease",
                    ),
                ),
                (
                    "num_relatives_chd",
                    models.IntegerField(
                        default=0,
                        help_text="Number of relatives with CHD",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "family_history_details",
                    models.TextField(
                        blank=True, help_text="Details about family history", null=True
                    ),
                ),
                ("has_hypertension", models.BooleanField(default=False)),
                ("has_diabetes", models.BooleanField(default=False)),
                ("has_high_cholesterol", models.BooleanField(default=False)),
                ("has_obesity", models.BooleanField(default=False)),
                ("is_smoker", models.BooleanField(default=False)),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("active", "Active"),
                            ("very_active", "Very Active"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("other_health_issues", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CoffeeConsumption",
        ),
        migrations.AddIndex(
            model_name="bloodpressureentry",
            index=models.Index(
                fields=["user", "-measured_at"], name="coffee_bloo_user_id_98b3e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumedcoffee",
            index=models.Index(
                fields=["user", "-consumed_at"], name="coffee_cons_user_id_08c584_idx"
            ),
        ),
    ]
