# Generated by Django 5.1.7 on 2026-02-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coffee",
            "0007_coffee_caffeine_mg_bloodpressureentry_consumedcoffee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If True, recipe only appears in owner's recipe list and favorites, not in main recipe list",
            ),
        ),
    ]
