# Generated by Django 6.0.2 on 2026-02-19 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0008_add_is_private_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumedcoffee",
            name="consumed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
