# Generated by Django 5.1.7 on 2025-05-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_2fa_enabled",
            new_name="twofa",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_special_admin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="plain_password",
        ),
        migrations.AddField(
            model_name="customuser",
            name="twofa_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
