# Generated by Django 5.1.7 on 2025-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_special_admin",
            field=models.BooleanField(default=False),
        ),
    ]
