# Generated by Django 5.2.1 on 2025-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_special_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_currently_suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_suspicious_check_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="suspicious_activity_count",
            field=models.IntegerField(default=0),
        ),
    ]
