# Generated by Django 5.1.7 on 2026-02-03 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_is_banned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodPressureEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(
                        help_text="Systolic blood pressure (big number)"
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        help_text="Diastolic blood pressure (small number)"
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True, help_text="Heart rate/pulse", null=True
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this reading"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_pressure_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Pressure Entry",
                "verbose_name_plural": "Blood Pressure Entries",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="UserHealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True, help_text="Height in centimeters", null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True, help_text="Weight in kilograms", null=True
                    ),
                ),
                (
                    "has_family_history_chd",
                    models.BooleanField(
                        default=False,
                        help_text="Family history of coronary heart disease",
                    ),
                ),
                (
                    "num_relatives_chd",
                    models.IntegerField(
                        default=0, help_text="Number of relatives with CHD"
                    ),
                ),
                (
                    "family_history_details",
                    models.TextField(
                        blank=True, help_text="Details about family history"
                    ),
                ),
                ("has_hypertension", models.BooleanField(default=False)),
                ("has_diabetes", models.BooleanField(default=False)),
                ("has_high_cholesterol", models.BooleanField(default=False)),
                ("has_obesity", models.BooleanField(default=False)),
                (
                    "other_conditions",
                    models.TextField(blank=True, help_text="Other health conditions"),
                ),
                ("is_smoker", models.BooleanField(default=False)),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light activity"),
                            ("moderate", "Moderate activity"),
                            ("active", "Active"),
                            ("very_active", "Very active"),
                        ],
                        default="sedentary",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Health Profile",
                "verbose_name_plural": "User Health Profiles",
            },
        ),
    ]
