# Generated by Django 5.1.7 on 2026-02-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_bloodpressureentry_userhealthprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="BloodPressureEntry",
        ),
        migrations.DeleteModel(
            name="UserHealthProfile",
        ),
    ]
